### ISSUE TITLE
tangent vector calculation, Lesson 6 bis

### ISSUE THREAD

**Issue by XiaofanLinUS** [ssloy/tinyrenderer#107]
Is it possible to calculate tangent vector i using the following equations?
![Screen Shot 2022-06-26 at 7 49 55 PM](https://user-images.githubusercontent.com/18253914/175850948-65899a63-da4e-469f-9b43-63550cad0f0b.png)

It's an odd math question. But it is very tempting to create such equations.

I try in my code. Sometimes, matrix A is non-invertible. And I am curious why that happens.

Thanks!

**Comment by ssloy** [comment]
Nope, the system you are writing is degenerate. You can obtain the third line by subtracting the first line from the second one.

Provided that your model is okay (no degenerate triangles), the matrix A must be invertible, since it contains the model coordinates prior to any projection:
https://github.com/ssloy/tinyrenderer/blob/dbc5d9287610e993a09bce89dec459162c925abe/main.cpp#L41

**Comment by XiaofanLinUS** [comment]
Just realize it is a degenerate matrix. Thanks!
