### ISSUE TITLE
some question about the Perspective projection

### ISSUE THREAD

**Issue by ftdejo** [ssloy/tinyrenderer#13]
In the chapter four:
> So, if we want to compute a central projection with a camera (important!) camera located on the z-axis with distance c from the origin, then we embed the point into 4D by augmenting it with 1, then we multiply it with the following matrix, and retro-project it into 3D.

When it comes to chapters six,our eyes are based on (1, 1, 3) which is not the z-axis.And I wonder why this projection matrix is so simple.So I looked for some other materials,then found a more complicated [matrix](http://ogldev.atspace.co.uk/www/tutorial12/tutorial12.html):
![projection](http://ogldev.atspace.co.uk/www/tutorial12/12_11.png)

After scanning articels,I replace ur matrix with the new ones(include changing the lookat matrix's fourth column).But I get a strange pic.Could u explain the difference between the matrix above and yours?

**Comment by ssloy** [comment]
Well, for starters, in my code I do not have any fancy stuff like far/near planes. In my application the camera is always placed (by the means of lookat()) at the axis Z facing the origin; the projection is made onto the plane Oxy.

In real OpenGL the camera is always placed at the origin and the projection is made onto the near plane. I dislike the tutorial you cite because they use some dirty tricks (the coefficient 1 at the position (3,4)). Check this <a href="http://www.songho.ca/opengl/gl_projectionmatrix.html">tutorial</a> instead:

<img src="http://www.songho.ca/opengl/files/gl_projectionmatrix_eq25.png"/>

**Comment by ftdejo** [comment]
@ssloy 
thx!
I'm reading <tricks of the 3d game programming gurus>,which seems too old for today's computer.So I wonder if you can recommend me some easy-read material of texture and sampler (Better online).I've already got a huge to-read book list which I'm working on :(

**Comment by ssloy** [comment]
Sorry, I was not checking recent books. If you find anything good, do not hesitate to share the link :)
