### ISSUE TITLE
Question about lesson 3

### ISSUE THREAD

**Issue by vsian** [ssloy/tinyrenderer#47]
I found the output wrong when using the following code to render:
![image](https://user-images.githubusercontent.com/20728697/81137061-fc0c9600-8f8f-11ea-9478-2a4e69e659fe.png)
The outcome turns out to be like this:
![image](https://user-images.githubusercontent.com/20728697/81137074-09298500-8f90-11ea-8774-7fa835c3ac37.png)
After reviewing the code in lesson 2 I got code as follow:
![image](https://user-images.githubusercontent.com/20728697/81137009-c49de980-8f8f-11ea-80e4-4fce9d1da540.png)
And this works fine, but I'm still confused, why is that?

**Comment by AliMustafa731** [comment]
This happens because in the first code above you changed world coordinates to screen and saved it in variable (pts_world).
so that, when you computued CrossProduct for N, you used screen coordinates!! and not world coordinates.
so that, all colors are white because 2d triangle will be always orthogonal to your light direction (0, 0, -1) (Negative z-axis)
