### ISSUE TITLE
Very simple (but wrong) implementation of lesson 1

### ISSUE THREAD

**Issue by dirkjonker** [ssloy/tinyrenderer#72]
This is what I originally came up with. 

```c++
void line(int x0, int y0, int x1, int y1, TGAImage &image, TGAColor color) {
  const int dx = x1 - x0;
  const int dy = y1 - y0;

  const int pixel_count = std::max(std::abs(dx), std::abs(dy)) + 1;

  for (int i = 0; i < pixel_count; i++) {
    const int x = i * dx / pixel_count;
    const int y = i * dy / pixel_count;
    image.set(x0 + x, y0 + y, color);
  }
}
```
It seemed so simple that I didn't really believe it could be the right solution. It seemed to draw all kinds of lines without any issue and even renders the model at the end of the chapter reasonably well, albeit with thick lines?

![result](https://user-images.githubusercontent.com/11753054/110546914-6f8eaf00-812f-11eb-9a61-760a11148072.png)

The function does not draws thick lines, but apparently the same lines are drawn more than once, but in the opposite direction. This is where the algorithm breaks: it uses integer division so it has a bias towards one side of the line, meaning that a line in the opposite direction will be drawn with (slightly) different pixels, except for some cases where there is an ideal ratio between `dx` and `dy`.

Thought it was interesting anyway, and might be useful if you need something really ~fast~ simple that doesn't have to be very precise.

**Comment by DudeMartin** [comment]
This is a nice and simple implementation that produces a good result but I'm not sure if it is "really fast" relative to other line rasterization algorithms. Division is much slower than addition, subtraction, and multiplication (I've seen numbers in the ranges of 3-15x) so any gains from the simpler implementation are probably lost there. There is also that bias that you mentioned caused by the fact that integer division drops the fractional part which does not happen with the other math operations. With that said, this could be a good example for explaining the drawbacks of a naive implementation and how they're solved by a proper line rasterization algorithm like [Bresenham's](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm).

**Comment by dirkjonker** [comment]
You are right, integer division indeed seems to be very slow. I didn't know about that, thanks!
