### ISSUE TITLE
some questions about lesson4

### ISSUE THREAD

**Issue by Wastexin** [ssloy/tinyrenderer#86]
1. why in the viewport matrix we need to change the depth(the z axis)
the code of viewport is follow:
```
Matrix viewport(int x, int y, int w, int h,int depth) {
    Matrix m = Matrix::identity(4);
    m[0][3] = x+w/2.f;
    m[1][3] = y+h/2.f;
    m[2][3] = depth/3.f; // why?

    m[0][0] = w/2.f;
    m[1][1] = h/2.f;
    m[2][2] = depth/3.f;  // why?
    return m;
}
```
**in my understanding,that viewport matrix is only need to change the scale of x and y**
2. I found a problem in the code of lesson 4 final,code is [here](https://github.com/ssloy/tinyrenderer/tree/1cce85258d1f1cf75fd10fe4d62ebfdb669f8cf9),the code i wrote by myself follow the lesson show the same problem.
the problem is that if i turn the camera and the light to the head's back, we wil see a mouse,it is impossible,i dont know what cause the problem,i will show the image of the back code(i have remove the texture)
![image](https://user-images.githubusercontent.com/25281390/142870049-a304428a-3c13-4913-880d-507694e6cd61.png)

3、finally,thanks for ssloy starting this project,i have learned a lot from this,thank you ! i am a beginer of cg,i dont know whether my understanding is right

**Comment by ssloy** [comment]
1. It is an old code that worked with integer depth values, it was removed in newer versions

https://github.com/ssloy/tinyrenderer/blob/d5355f5d23b5bb3ca82eb7c02702c870f5fc1c29/our_gl.cpp#L9

2. I suppose that you see the mouth because you have skipped the z-buffer lesson, and the hidden parts removal is made with a simple backface culling, so the result is completely okay.

Thank you for your kind words!

**Comment by Wastexin** [comment]
thank you for your reply！

**Comment by Wastexin** [comment]
> 

thank you for your reply！
